name: react-navigation-plugin
description: Incluir lib de navegação em um projeto React Native
display-name: React Navigation
picture: plugin.png
category: frontend # Ref: https://docs.stackspot.com/docs/create-stacks/yaml-files/plugin/#category
compatibility:
  - react native
  - typescript
  - javascript
about: docs/about.md
usage: docs/usage.md
use-case: docs/use-case.md
implementation: docs/implementation.md
technologies: # Ref: https://docs.stackspot.com/docs/create-stacks/yaml-files/yaml/#technologies
  - "JavaScript"
  - "React"
  - "Typescript"
types:
  - app

hooks:
  - type: run
    trigger: before-render
    commands:
      - yarn add @react-navigation/native
      - npx expo install react-native-screens react-native-safe-area-context
  - type: run
    trigger: after-render
    mac:
      - npx pod-install ios
  - type: edit
    trigger: after-render
    path: src/index.js
    changes:
      # - insert:
      #     line: 0
      #     value: |
      #       {% raw %}
      #       Teste
      #       {% endraw %}
      - search:
          string: "} from 'react-native';"
          insert-after:
            value: |
              {% raw %}
              import { NavigationContainer } from '@react-navigation/native';
              {% endraw %}
          when:
            not-exists: "import { NavigationContainer } from '@react-navigation/native';"
      - search:
          string: "return ("
          insert-after:
            value: "    <NavigationContainer>"
          when:
            not-exists: "<NavigationContainer>"
      - search:
          string: "</View>"
          insert-after:
            value: "    </NavigationContainer>"
          when:
            not-exists: "</NavigationContainer>"