name: react-navigation-plugin
description: Incluir lib de navegação em um projeto React Native
display-name: React Navigation
picture: plugin.png
category: frontend # Ref: https://docs.stackspot.com/docs/create-stacks/yaml-files/plugin/#category
compatibility:
  - react native
  - typescript
  - javascript
about: docs/about.md
usage: docs/usage.md
use-case: docs/use-case.md
implementation: docs/implementation.md
technologies: # Ref: https://docs.stackspot.com/docs/create-stacks/yaml-files/yaml/#technologies
  - "JavaScript"
  - "React"
  - "Typescript"
types:
  - app
inputs:
  - label: Input Example
    type: text
    name: example
    default: any text
  # - label: Example of number
  #   type: int
  #   name: any_number
  #   default: "10"
  # - label: Example of list
  #   type: multiselect
  #   name: any_list
  #   items:
  #     - item1
  #     - item2

hooks:
  - type: run
    trigger: before-render
    commands:
      - yarn add @react-navigation/native
      - npx expo install react-native-screens react-native-safe-area-context
  - type: run
    trigger: after-render
    mac:
      - npx pod-install ios